using SniffExplorer.Core.Packets;
using SniffExplorer.Core.Packets.Parsing;
using SniffExplorer.Core.Utils;
using System;

namespace SniffExplorer.Cataclysm
{
    public sealed class OpcodeProvider : IOpcodeProvider
    {
        private static BiDictionary<Opcodes, uint> _serverOpcodes = new BiDictionary<Opcodes, uint>()
        {

        };

        private static BiDictionary<Opcodes, uint> _clientOpcodes = new BiDictionary<Opcodes, uint>()
        {
            { Opcodes.CMSG_ACCEPT_LEVEL_GRANT                           , 0x0205 },
            { Opcodes.CMSG_ACCEPT_TRADE                                 , 0x7110 },
            { Opcodes.CMSG_ACTIVATE_TAXI                                , 0x6E06 },
            /// { Opcodes.CMSG_ACTIVATETAXIEXPRESS                          , 0x0515 },
            { Opcodes.CMSG_ADDON_LIST                                   , 0x0954 },
            { Opcodes.CMSG_ADD_FRIEND                                   , 0x6527 },
            { Opcodes.CMSG_ADD_IGNORE                                   , 0x4726 },
            /// { Opcodes.CMSG_ADD_VOICE_IGNORE                             , 0x0F06 },
            { Opcodes.CMSG_ALTER_APPEARANCE                             , 0x0914 },
            { Opcodes.CMSG_AREA_TRIGGER                                 , 0x0937 },
            { Opcodes.CMSG_AREA_SPIRIT_HEALER_QUERY                     , 0x4907 },
            { Opcodes.CMSG_AREA_SPIRIT_HEALER_QUEUE                     , 0x4815 },
            /// { Opcodes.CMSG_ARENA_TEAM_ACCEPT                            , 0x2A25 },
            /// { Opcodes.CMSG_ARENA_TEAM_CREATE                            , 0x04A1 },
            /// { Opcodes.CMSG_ARENA_TEAM_DECLINE                           , 0x6925 },
            /// { Opcodes.CMSG_ARENA_TEAM_DISBAND                           , 0x6504 },
            /// { Opcodes.CMSG_ARENA_TEAM_INVITE                            , 0x2F27 },
            /// { Opcodes.CMSG_ARENA_TEAM_LEADER                            , 0x4204 },
            /// { Opcodes.CMSG_ARENA_TEAM_LEAVE                             , 0x0E16 },
            /// { Opcodes.CMSG_ARENA_TEAM_QUERY                             , 0x0514 },
            /// { Opcodes.CMSG_ARENA_TEAM_REMOVE                            , 0x2F05 },
            /// { Opcodes.CMSG_ARENA_TEAM_ROSTER                            , 0x6F37 },
            { Opcodes.CMSG_ATTACK_STOP                                  , 0x4106 },
            { Opcodes.CMSG_ATTACK_SWING                                 , 0x0926 },
            { Opcodes.CMSG_AUCTION_LIST_BIDDER_ITEMS                    , 0x6937 },
            { Opcodes.CMSG_AUCTION_LIST_ITEMS                           , 0x0324 },
            { Opcodes.CMSG_AUCTION_LIST_OWNER_ITEMS                     , 0x0206 },
            { Opcodes.CMSG_AUCTION_LIST_PENDING_SALES                   , 0x2C17 },
            { Opcodes.CMSG_AUCTION_PLACE_BID                            , 0x2306 },
            { Opcodes.CMSG_AUCTION_REMOVE_ITEM                          , 0x6426 },
            { Opcodes.CMSG_AUCTION_SELL_ITEM                            , 0x4A06 },
            { Opcodes.CMSG_AUTH_SESSION                                 , 0x0449 },
            { Opcodes.CMSG_AUTOBANK_ITEM                                , 0x2537 },
            // { Opcodes.CMSG_AUTOEQUIP_GROUND_ITEM                        , 0x0000 },
            { Opcodes.CMSG_AUTO_EQUIP_ITEM                              , 0x4304 },
            { Opcodes.CMSG_AUTO_EQUIP_ITEM_SLOT                         , 0x4A17 },
            { Opcodes.CMSG_AUTO_STORE_BAG_ITEM                          , 0x0236 },
            { Opcodes.CMSG_AUTOSTORE_BANK_ITEM                          , 0x0607 },
            // { Opcodes.CMSG_AUTO_STORE_GROUND_ITEM                        , 0x0000 },
            /// { Opcodes.CMSG_AUTOSTORE_LOOT_ITEM                          , 0x0E34 },
            { Opcodes.CMSG_GUILD_AUTO_DECLINE_INVITATION                , 0x2034 },
            { Opcodes.CMSG_BANKER_ACTIVATE                              , 0x0005 },
            // { Opcodes.CMSG_BATTLEFIELD_JOIN                             , 0x0000 },
            { Opcodes.CMSG_BATTLEFIELD_LEAVE                            , 0x3018 },
            { Opcodes.CMSG_BATTLEFIELD_LIST                             , 0x3814 },
            /// { Opcodes.CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE        , 0x05A3 },
            /// { Opcodes.CMSG_BATTLEFIELD_MGR_EXIT_REQUEST                 , 0x2490 },
            /// { Opcodes.CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE        , 0x0413 },
            /// { Opcodes.CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST                , 0x710C },
            { Opcodes.CMSG_BATTLEFIELD_PORT                             , 0x711A },
            // { Opcodes.CMSG_BATTLEFIELD_REQUEST_SCORE_DATA               , 0x0000 },
            /// { Opcodes.CMSG_BATTLEFIELD_STATUS                           , 0x2500 },
            { Opcodes.SMSG_BATTLEGROUND_PLAYER_POSITIONS                , 0x3902 },
            { Opcodes.CMSG_BATTLEMASTER_JOIN                            , 0x7902 },
            { Opcodes.CMSG_BATTLEMASTER_JOIN_ARENA                      , 0x701C },
            { Opcodes.CMSG_JOIN_RATED_BATTLEGROUND                      , 0x3B18 },
            { Opcodes.CMSG_BATTLEMASTER_HELLO                           , 0x0234 },
            { Opcodes.CMSG_BEGIN_TRADE                                  , 0x721E },
            { Opcodes.CMSG_BINDER_ACTIVATE                              , 0x4006 },
            // { Opcodes.CMSG_BOT_DETECTED2                                , 0x0000 },
            { Opcodes.CMSG_BUG_REPORT                                   , 0x4035 },
            { Opcodes.CMSG_BUSY_TRADE                                   , 0x331C },
            { Opcodes.CMSG_BUY_BACK_ITEM                                , 0x6C17 },
            { Opcodes.CMSG_BUY_BANK_SLOT                                , 0x0425 },
            { Opcodes.CMSG_BUY_ITEM                                     , 0x0736 },
            { Opcodes.CMSG_CALENDAR_ADD_EVENT                           , 0x0726 },
            /// { Opcodes.CMSG_CALENDAR_ARENA_TEAM                          , 0x0204 },
            { Opcodes.CMSG_CALENDAR_COMPLAIN                            , 0x4C36 },
            // { Opcodes.CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP                , 0x0000 },
            { Opcodes.CMSG_CALENDAR_COPY_EVENT                          , 0x0207 },
            { Opcodes.CMSG_CALENDAR_EVENT_INVITE                        , 0x2435 },
            { Opcodes.CMSG_CALENDAR_EVENT_MODERATOR_STATUS              , 0x6B35 },
            /// { Opcodes.CMSG_CALENDAR_EVENT_REMOVE_INVITE                 , 0x4337 },
            { Opcodes.CMSG_CALENDAR_EVENT_RSVP                          , 0x0227 },
            { Opcodes.CMSG_CALENDAR_EVENT_SIGN_UP                       , 0x6606 },
            { Opcodes.CMSG_CALENDAR_EVENT_STATUS                        , 0x2D24 },
            /// { Opcodes.CMSG_CALENDAR_GET_CALENDAR                        , 0x2814 },
            { Opcodes.CMSG_CALENDAR_GET_EVENT                           , 0x6416 },
            { Opcodes.CMSG_CALENDAR_GET_NUM_PENDING                     , 0x4D05 },
            { Opcodes.CMSG_CALENDAR_GUILD_FILTER                        , 0x4A16 },
            { Opcodes.CMSG_CALENDAR_REMOVE_EVENT                        , 0x6636 },
            { Opcodes.CMSG_CALENDAR_UPDATE_EVENT                        , 0x2114 },
            { Opcodes.CMSG_CANCEL_AURA                                  , 0x0E26 },
            { Opcodes.CMSG_CANCEL_AUTO_REPEAT_SPELL                     , 0x6C35 },
            { Opcodes.CMSG_CANCEL_CAST                                  , 0x0115 },
            { Opcodes.CMSG_CANCEL_CHANNELLING                           , 0x6C25 },
            { Opcodes.CMSG_CANCEL_GROWTH_AURA                           , 0x0000 },
            { Opcodes.CMSG_CANCEL_MOUNT_AURA                            , 0x0635 },
            { Opcodes.CMSG_CANCEL_QUEUED_SPELL                          , 0x7B1C },
            { Opcodes.CMSG_CANCEL_TEMP_ENCHANTMENT                      , 0x6C37 },
            { Opcodes.CMSG_CANCEL_TRADE                                 , 0x731E },
            { Opcodes.CMSG_CAST_SPELL                                   , 0x4C07 },
            /// { Opcodes.CMSG_CHANGEPLAYER_DIFFICULTY                      , 0x6107 },
            /// { Opcodes.CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE           , 0x7310 },
            { Opcodes.CMSG_CHAT_CHANNEL_ANNOUNCEMENTS                   , 0x1146 },
            { Opcodes.CMSG_CHAT_CHANNEL_BAN                             , 0x3D56 },
            { Opcodes.CMSG_CHAT_CHANNEL_DISPLAY_LIST                    , 0x2144 },
            { Opcodes.CMSG_CHAT_CHANNEL_INVITE                          , 0x0144 },
            { Opcodes.CMSG_CHAT_CHANNEL_KICK                            , 0x3156 },
            { Opcodes.CMSG_CHAT_CHANNEL_LIST                            , 0x1556 },
            { Opcodes.CMSG_CHAT_CHANNEL_MODERATE                        , 0x2944 },
            { Opcodes.CMSG_CHAT_CHANNEL_MODERATOR                       , 0x0146 },
            { Opcodes.CMSG_CHAT_CHANNEL_MUTE                            , 0x2554 },
            { Opcodes.CMSG_CHAT_CHANNEL_OWNER                           , 0x3D44 },
            { Opcodes.CMSG_CHAT_CHANNEL_PASSWORD                        , 0x2556 },
            /// { Opcodes.CMSG_CHANNEL_ROSTER_INFO                          , 0x3546 },
            { Opcodes.CMSG_CHAT_CHANNEL_SET_OWNER                       , 0x3556 },
            { Opcodes.CMSG_CHAT_CHANNEL_SILENCE_ALL                     , 0x2154 },
            /// { Opcodes.CMSG_CHANNEL_SILENCE_VOICE                        , 0x2D54 },
            { Opcodes.CMSG_CHAT_CHANNEL_UNBAN                           , 0x2D46 },
            { Opcodes.CMSG_CHAT_CHANNEL_UNMODERATOR                     , 0x1954 },
            { Opcodes.CMSG_CHAT_CHANNEL_UNMUTE                          , 0x3554 },
            { Opcodes.CMSG_CHAT_CHANNEL_UNSILENCE_ALL                   , 0x2546 },
            /// { Opcodes.CMSG_CHAT_CHANNEL_UNSILENCE_VOICE                 , 0x3146 },
            /// { Opcodes.CMSG_CHAT_CHANNEL_VOICE_OFF                       , 0x3144 },
            /// { Opcodes.CMSG_CHAT_CHANNEL_VOICE_ON                        , 0x1144 },
            { Opcodes.CMSG_CHAT_LEAVE_CHANNEL                           , 0x2D56 },
            { Opcodes.CMSG_CREATE_CHARACTER                             , 0x4A36 },
            { Opcodes.CMSG_CHAR_CUSTOMIZE                               , 0x2C34 },
            { Opcodes.CMSG_CHAR_DELETE                                  , 0x6425 },
            { Opcodes.CMSG_ENUM_CHARACTERS                              , 0x0502 },
            { Opcodes.CMSG_CHAR_FACTION_CHANGE                          , 0x2735 },
            // { Opcodes.CMSG_COMPLETED_ARTIFACTS                          , 0x0000 },
            { Opcodes.CMSG_CHAR_RACE_CHANGE                             , 0x0D24 },
            { Opcodes.CMSG_CHARACTER_RENAME_REQUEST                     , 0x2327 },
            { Opcodes.CMSG_CHAT_REPORT_FILTERED                         , 0x0946 },
            { Opcodes.CMSG_CHAT_REPORT_IGNORED                          , 0x0D54 },
            /// { Opcodes.CMSG_CLEAR_CHANNEL_WATCH                          , 0x2604 },
            { Opcodes.CMSG_CLEAR_RAID_MARKER                            , 0x7300 },
            { Opcodes.CMSG_CLEAR_TRADE_ITEM                             , 0x7018 },
            { Opcodes.CMSG_COMMENTATOR_ENABLE                           , 0x0B07 },
            { Opcodes.CMSG_COMMENTATOR_ENTER_INSTANCE                   , 0x4105 },
            { Opcodes.CMSG_COMMENTATOR_EXIT_INSTANCE                    , 0x6136 },
            { Opcodes.CMSG_COMMENTATOR_GET_MAP_INFO                     , 0x0026 },
            { Opcodes.CMSG_COMMENTATOR_GET_PLAYER_COOLDOWNS             , 0x2412 },
            { Opcodes.CMSG_COMMENTATOR_GET_PLAYER_INFO                  , 0x0D14 },
            /// { Opcodes.CMSG_COMMENTATOR_INSTANCE_COMMAND                 , 0x0917 },
            /// { Opcodes.CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND           , 0x0025 },
            { Opcodes.CMSG_COMMENTATOR_START_WARGAME                    , 0x25A0 },
            { Opcodes.CMSG_COMPLAINT                                    , 0x0427 },
            { Opcodes.CMSG_COMPLETE_CINEMATIC                           , 0x2116 },
            { Opcodes.CMSG_COMPLETE_MOVIE                               , 0x4136 },
            { Opcodes.CMSG_CONNECT_TO_FAILED                            , 0x2533 },
            { Opcodes.CMSG_SEND_CONTACT_LIST                            , 0x4534 },
            { Opcodes.CMSG_QUERY_CORPSE_LOCATION_FROM_CLIENT            , 0x6205 },
            { Opcodes.CMSG_QUERY_CREATURE                               , 0x2706 },
            /// { Opcodes.CMSG_DANCE_QUERY                                  , 0x4E07 },
            // { Opcodes.CMSG_DECLINE_CHANNEL_INVITE                       , 0x0000 },
            { Opcodes.CMSG_DEL_FRIEND                                   , 0x6A15 },
            { Opcodes.CMSG_DEL_IGNORE                                   , 0x6D26 },
            /// { Opcodes.CMSG_DEL_VOICE_IGNORE                             , 0x0024 },
            { Opcodes.CMSG_DESTROY_ITEM                                 , 0x4A27 },
            /// { Opcodes.CMSG_DISMISS_CONTROLLED_VEHICLE                   , 0x3218 },
            { Opcodes.CMSG_DISMISS_CRITTER                              , 0x4227 },
            { Opcodes.CMSG_DUEL_ACCEPTED                                , 0x2136 },
            { Opcodes.CMSG_DUEL_CANCELLED                               , 0x6624 },
            { Opcodes.CMSG_EJECT_PASSENGER                              , 0x6927 },
            { Opcodes.CMSG_EMOTE                                        , 0x4C26 },
            { Opcodes.CMSG_ENABLE_TAXI_NODE                             , 0x0C16 },
            { Opcodes.CMSG_ENABLE_NAGLE                                 , 0x4449 },
            { Opcodes.CMSG_DELETE_EQUIPMENT_SET                         , 0x4D07 },
            { Opcodes.CMSG_SAVE_EQUIPMENT_SET                           , 0x4F27 },
            { Opcodes.CMSG_USE_EQUIPMENT_SET                            , 0x0417 },
            { Opcodes.CMSG_FAR_SIGHT                                    , 0x4835 },
            { Opcodes.CMSG_MOVE_FORCE_ROOT_ACK                          , 0x701E },
            { Opcodes.CMSG_MOVE_FORCE_UNROOT_ACK                        , 0x7808 },
            { Opcodes.CMSG_QUERY_GAME_OBJECT                            , 0x4017 },
            { Opcodes.CMSG_GAME_OBJ_REPORT_USE                          , 0x4827 },
            { Opcodes.CMSG_GAME_OBJ_USE                                 , 0x4E17 },
            // { Opcodes.CMSG_GAMESPEED_SET                                , 0x0000 },
            // { Opcodes.CMSG_GAMETIME_SET                                 , 0x0000 },
            // { Opcodes.CMSG_GETDEATHBINDZONE                             , 0x0000 },
            { Opcodes.CMSG_MAIL_GET_LIST                                , 0x4D37 },
            { Opcodes.CMSG_GET_MIRROR_IMAGE_DATA                        , 0x0C25 },
            // { Opcodes.CMSG_GHOST                                        , 0x0000 },
            /// { Opcodes.CMSG_GMRESPONSE_RESOLVE                           , 0x6506 },
            /// { Opcodes.CMSG_GMSURVEY_SUBMIT                              , 0x2724 },
            /// { Opcodes.CMSG_GMTICKET_CREATE                              , 0x0137 },
            /// { Opcodes.CMSG_GMTICKET_DELETETICKET                        , 0x6B14 },
            /// { Opcodes.CMSG_GMTICKET_GETTICKET                           , 0x0326 },
            /// { Opcodes.CMSG_GMTICKET_SYSTEMSTATUS                        , 0x4205 },
            /// { Opcodes.CMSG_GMTICKET_UPDATETEXT                          , 0x0636 },
            // { Opcodes.CMSG_GM_INVIS                                     , 0x0000 },
            // { Opcodes.CMSG_GM_NUKE                                      , 0x0000 },
            /// { Opcodes.CMSG_GM_REPORT_LAG                                , 0x6726 },
            // { Opcodes.CMSG_GM_SET_SECURITY_GROUP                        , 0x0000 },
            { Opcodes.CMSG_TALK_TO_GOSSIP                               , 0x4525 },
            { Opcodes.CMSG_GOSSIP_SELECT_OPTION                         , 0x0216 },
            { Opcodes.CMSG_GRANT_LEVEL                                  , 0x6D16 },
            { Opcodes.CMSG_SET_ASSISTANT_LEADER                         , 0x6025 },
            // { Opcodes.CMSG_GROUP_CANCEL                                 , 0x0000 },
            { Opcodes.CMSG_CHANGE_SUB_GROUP                             , 0x4124 },
            { Opcodes.CMSG_LEAVE_GROUP                                  , 0x2804 },
            { Opcodes.CMSG_PARTY_INVITE                                 , 0x0513 },
            { Opcodes.CMSG_PARTY_INVITE_RESPONSE                        , 0x0410 },
            { Opcodes.CMSG_CONVERT_RAID                                 , 0x6E27 },
            { Opcodes.CMSG_REQUEST_PARTY_JOIN_UPDATES                   , 0x2583 },
            { Opcodes.SMSG_GROUP_NEW_LEADER                             , 0x4C17 }, //!
            { Opcodes.CMSG_SET_ROLE                                     , 0x25B1 },
            { Opcodes.CMSG_SWAP_SUB_GROUPS                              , 0x0034 },
            // { Opcodes.CMSG_GROUP_UNINVITE                               , 0x0000 },
            { Opcodes.CMSG_PARTY_UNINVITE                               , 0x2E07 },
            { Opcodes.CMSG_ACCEPT_GUILD_INVITE                          , 0x2531 },
            { Opcodes.CMSG_GUILD_GET_ACHIEVEMENT_MEMBERS                , 0x3025 },
            { Opcodes.CMSG_GUILD_SET_FOCUSED_ACHIEVEMENT                , 0x3235 },
            { Opcodes.CMSG_GUILD_ADD_RANK                               , 0x3030 },
            { Opcodes.CMSG_GUILD_ASSIGN_MEMBER_RANK                     , 0x3032 },
            { Opcodes.CMSG_GUILD_BANK_ACTIVATE                          , 0x2E37 },
            { Opcodes.CMSG_GUILD_BANK_BUY_TAB                           , 0x0C37 },
            { Opcodes.CMSG_GUILD_BANK_DEPOSIT_MONEY                     , 0x0707 },
            { Opcodes.CMSG_GUILD_BANK_LOG_QUERY                         , 0x3224 },
            { Opcodes.CMSG_GUILD_BANK_REMAINING_WITHDRAW_MONEY_QUERY    , 0x1225 },
            // { Opcodes.CMSG_GUILD_BANK_NOTE                              , 0x0000 },
            { Opcodes.CMSG_GUILD_BANK_QUERY_TAB                         , 0x2E35 },
            { Opcodes.CMSG_GUILD_BANK_TEXT_QUERY                        , 0x3220 },
            { Opcodes.CMSG_GUILD_BANK_SWAP_ITEMS                        , 0x2315 },
            { Opcodes.CMSG_GUILD_BANK_UPDATE_TAB                        , 0x0106 },
            { Opcodes.CMSG_GUILD_BANK_WITHDRAW_MONEY                    , 0x0037 },
            { Opcodes.CMSG_GUILD_CHANGE_NAME_REQUEST                    , 0x1232 },
            { Opcodes.CMSG_DECLINE_GUILD_INVITES                        , 0x3231 },
            { Opcodes.CMSG_GUILD_DELETE_RANK                            , 0x3234 },
            { Opcodes.CMSG_GUILD_DEMOTE_MEMBER                          , 0x1020 },
            { Opcodes.CMSG_GUILD_DELETE                                 , 0x3226 },
            { Opcodes.CMSG_GUILD_EVENT_LOG_QUERY                        , 0x1220 },
            // { Opcodes.CMSG_GUILD_INFO                                   , 0x0000 },
            { Opcodes.CMSG_GUILD_UPDATE_INFO_TEXT                       , 0x3227 },
            { Opcodes.CMSG_ACCEPT_GUILD_INVITE                          , 0x24B0 },
            { Opcodes.CMSG_GUILD_LEAVE                                  , 0x1021 },
            { Opcodes.CMSG_GUILD_MEMBER_SEND_SOR_REQUEST                , 0x3225 },
            { Opcodes.CMSG_GUILD_UPDATE_MOTD_TEXT                       , 0x1035 },
            { Opcodes.CMSG_GUILD_NEWS_UPDATE_STICKY                     , 0x3223 },
            { Opcodes.CMSG_GUILD_PERMISSIONS_QUERY                      , 0x3022 },
            { Opcodes.CMSG_GUILD_PROMOTE_MEMBER                         , 0x1030 },
            /// { Opcodes.CMSG_GUILD_QUERY                                  , 0x4426 },
            { Opcodes.CMSG_GUILD_QUERY_NEWS                             , 0x3020 },
            { Opcodes.CMSG_GUILD_GET_RANKS                              , 0x1026 },
            { Opcodes.CMSG_GUILD_OFFICER_REMOVE_MEMBER                  , 0x1231 },
            { Opcodes.CMSG_GUILD_REPLACE_GUILD_MASTER                   , 0x1034 },
            { Opcodes.CMSG_GUILD_CHALLENGE_UPDATE_REQUEST               , 0x1224 },
            /// { Opcodes.CMSG_GUILD_REQUEST_MAX_DAILY_XP                   , 0x3232 },
            { Opcodes.CMSG_REQUEST_GUILD_PARTY_STATE                    , 0x3900 },
            { Opcodes.CMSG_GUILD_GET_ROSTER                             , 0x1226 },
            { Opcodes.CMSG_GUILD_SET_ACHIEVEMENT_TRACKING               , 0x1027 },
            { Opcodes.CMSG_GUILD_SET_GUILD_MASTER                       , 0x3034 },
            { Opcodes.CMSG_GUILD_SET_MEMBER_NOTE                        , 0x1233 },
            { Opcodes.CMSG_GUILD_SET_RANK_PERMISSIONS                   , 0x1024 },
            { Opcodes.CMSG_GUILD_SHIFT_RANK                             , 0x1221 },
            { Opcodes.CMSG_BATTLEFIELD_LEAVE                            , 0x4B34 },
            { Opcodes.CMSG_IGNORE_TRADE                                 , 0x7112 },
            { Opcodes.CMSG_INITIATE_TRADE                               , 0x7916 },
            { Opcodes.CMSG_INSPECT                                      , 0x0927 },
            { Opcodes.CMSG_INSPECT_PVP                                  , 0x791E },
            { Opcodes.CMSG_INSTANCE_LOCK_RESPONSE                       , 0x6234 },
            { Opcodes.CMSG_ITEM_PURCHASE_REFUND                         , 0x6134 },
            /// { Opcodes.CMSG_ITEM_REFUND_INFO                             , 0x2206 },
            { Opcodes.CMSG_ITEM_TEXT_QUERY                              , 0x2406 },
            { Opcodes.CMSG_CHAT_JOIN_CHANNEL                            , 0x0156 },
            { Opcodes.CMSG_KEEP_ALIVE                                   , 0x0015 },
            { Opcodes.CMSG_LEARN_PREVIEW_TALENTS                        , 0x2415 },
            { Opcodes.CMSG_LEARN_PREVIEW_TALENTS_PET                    , 0x6E24 },
            { Opcodes.CMSG_LEARN_TALENTS                                , 0x0306 },
            { Opcodes.CMSG_LFG_LIST_GET_STATUS                          , 0x2581 },
            { Opcodes.CMSG_LFG_LIST_JOIN                                , 0x2430 },
            { Opcodes.CMSG_LFG_LIST_LEAVE                               , 0x2433 },
            { Opcodes.CMSG_LFG_LIST_SEARCH                              , 0x0531 },
            { Opcodes.CMSG_DF_LEAVE                                     , 0x0500 },
            { Opcodes.CMSG_INSTANCE_LOCK_RESPONSE                       , 0x0412 },
            { Opcodes.CMSG_DF_PROPOSAL_RESPONSE                         , 0x0403 },
            { Opcodes.CMSG_DF_BOOT_PLAYER_VOTE                          , 0x04B3 },
            /// { Opcodes.CMSG_LFG_SET_COMMENT                              , 0x0530 },
            { Opcodes.CMSG_DF_SET_ROLES                                 , 0x0480 },
            { Opcodes.CMSG_DF_TELEPORT                                  , 0x2482 },
            { Opcodes.CMSG_LF_GUILD_ADD_RECRUIT                         , 0x4448 },
            { Opcodes.CMSG_LF_GUILD_BROWSE                              , 0x0548 },
            { Opcodes.CMSG_LF_GUILD_DECLINE_RECRUIT                     , 0x1031 },
            { Opcodes.CMSG_LF_GUILD_GET_APPLICATIONS                    , 0x1230 },
            { Opcodes.CMSG_LF_GUILD_GET_RECRUITS                        , 0x3230 },
            { Opcodes.CMSG_LF_GUILD_GET_GUILD_POST                      , 0x3237 },
            { Opcodes.CMSG_LF_GUILD_REMOVE_RECRUIT                      , 0x3027 },
            { Opcodes.CMSG_LF_GUILD_SET_GUILD_POST                      , 0x0448 },
            { Opcodes.CMSG_LIST_INVENTORY                               , 0x2806 },
            { Opcodes.CMSG_LOADING_SCREEN_NOTIFY                        , 0x2422 },
            { Opcodes.CMSG_LOGOUT_CANCEL                                , 0x2324 },
            { Opcodes.CMSG_LOGOUT_REQUEST                               , 0x0A25 },
            { Opcodes.CMSG_LOG_DISCONNECT                               , 0x446D },
            /// { Opcodes.CMSG_LOOT                                         , 0x0127 },
            /// { Opcodes.CMSG_LOOT_CURRENCY                                , 0x781C },
            { Opcodes.CMSG_DO_MASTER_LOOT_ROLL                          , 0x4F35 },
            { Opcodes.CMSG_SET_LOOT_METHOD                              , 0x2F24 },
            { Opcodes.CMSG_LOOT_MONEY                                   , 0x6227 },
            { Opcodes.CMSG_LOOT_RELEASE                                 , 0x2007 },
            { Opcodes.CMSG_LOOT_ROLL                                    , 0x6934 },
            { Opcodes.CMSG_MAIL_CREATE_TEXT_ITEM                        , 0x0B14 },
            { Opcodes.CMSG_MAIL_DELETE                                  , 0x6104 },
            { Opcodes.CMSG_MAIL_MARK_AS_READ                            , 0x0C07 },
            { Opcodes.CMSG_MAIL_RETURN_TO_SENDER                        , 0x0816 },
            { Opcodes.CMSG_MAIL_TAKE_ITEM                               , 0x2B06 },
            { Opcodes.CMSG_MAIL_TAKE_MONEY                              , 0x4034 },
            // { Opcodes.CMSG_MEETINGSTONE_INFO                            , 0x0000 },
            { Opcodes.CMSG_CHAT_ADDON_MESSAGE_INSTANCE_CHAT             , 0x0D46 },
            { Opcodes.CMSG_CHAT_ADDON_MESSAGE_GUILD                     , 0x0544 },
            { Opcodes.CMSG_CHAT_ADDON_MESSAGE_OFFICER                   , 0x3954 },
            { Opcodes.CMSG_CHAT_ADDON_MESSAGE_PARTY                     , 0x0546 },
            { Opcodes.CMSG_CHAT_ADDON_MESSAGE_RAID                      , 0x1D56 },
            { Opcodes.CMSG_CHAT_ADDON_MESSAGE_WHISPER                   , 0x2146 },
            { Opcodes.CMSG_CHAT_MESSAGE_AFK                             , 0x0D44 },
            { Opcodes.CMSG_CHAT_MESSAGE_INSTANCE_CHAT                   , 0x2156 },
            { Opcodes.CMSG_CHAT_MESSAGE_CHANNEL                         , 0x1D44 },
            { Opcodes.CMSG_CHAT_MESSAGE_DND                             , 0x2946 },
            { Opcodes.CMSG_CHAT_MESSAGE_EMOTE                           , 0x1156 },
            { Opcodes.CMSG_CHAT_MESSAGE_GUILD                           , 0x3956 },
            { Opcodes.CMSG_CHAT_MESSAGE_OFFICER                         , 0x1946 },
            { Opcodes.CMSG_CHAT_MESSAGE_PARTY                           , 0x1D46 },
            { Opcodes.CMSG_CHAT_MESSAGE_RAID                            , 0x2D44 },
            { Opcodes.CMSG_CHAT_MESSAGE_RAID_WARNING                    , 0x0944 },
            { Opcodes.CMSG_CHAT_MESSAGE_SAY                             , 0x1154 },
            { Opcodes.CMSG_CHAT_MESSAGE_WHISPER                         , 0x0D56 },
            { Opcodes.CMSG_CHAT_MESSAGE_YELL                            , 0x3544 },
            /// { Opcodes.CMSG_MINIGAME_MOVE                                , 0x2A34 },
            { Opcodes.CMSG_MOUNT_SPECIAL_ANIM                           , 0x2807 },
            // { Opcodes.CMSG_MOVE_CHARM_TELEPORT_CHEAT                    , 0x0000 },
            { Opcodes.CMSG_MOVE_CHANGE_TRANSPORT                        , 0x3102 },
            // { Opcodes.CMSG_MOVE_ENABLE_SWIM_TO_FLY_TRANS_ACK            , 0x0000 },
            { Opcodes.CMSG_MOVE_FALL_RESET                              , 0x310A },
            { Opcodes.CMSG_MOVE_FEATHER_FALL_ACK                        , 0x3110 },
            { Opcodes.CMSG_MOVE_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK      , 0x310E },
            { Opcodes.CMSG_MOVE_FORCE_FLIGHT_SPEED_CHANGE_ACK           , 0x7314 },
            { Opcodes.CMSG_MOVE_FORCE_PITCH_RATE_CHANGE_ACK             , 0x3100 },
            { Opcodes.CMSG_MOVE_FORCE_RUN_BACK_SPEED_CHANGE_ACK         , 0x3216 },
            { Opcodes.CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK              , 0x7818 },
            { Opcodes.CMSG_MOVE_FORCE_SWIM_BACK_SPEED_CHANGE_ACK        , 0x7A16 },
            { Opcodes.CMSG_MOVE_FORCE_SWIM_SPEED_CHANGE_ACK             , 0x7A10 },
            { Opcodes.CMSG_MOVE_FORCE_TURN_RATE_CHANGE_ACK              , 0x7316 },
            { Opcodes.CMSG_MOVE_FORCE_WALK_SPEED_CHANGE_ACK             , 0x7210 },
            { Opcodes.CMSG_MOVE_GRAVITY_DISABLE_ACK                     , 0x3118 },
            { Opcodes.CMSG_MOVE_GRAVITY_ENABLE_ACK                      , 0x700A },
            { Opcodes.CMSG_MOVE_HOVER_ACK                               , 0x3318 },
            { Opcodes.CMSG_MOVE_KNOCK_BACK_ACK                          , 0x721C },
            /// { Opcodes.CMSG_MOVE_NOT_ACTIVE_MOVER                        , 0x7A1A },
            /// { Opcodes.CMSG_MOVE_SET_CAN_FLY                             , 0x720E },
            { Opcodes.CMSG_MOVE_SET_CAN_FLY_ACK                         , 0x790C },
            /// { Opcodes.CMSG_MOVE_SET_CAN_FLY_TO_SWIM_ACK                 , 0x3014 }, // old CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK
            { Opcodes.CMSG_MOVE_SET_COLLISION_HEIGHT_ACK                , 0x7114 },
            // { Opcodes.CMSG_MOVE_SET_RELATIVE_POSITION                   , 0x0000 },
            // { Opcodes.CMSG_MOVE_SET_VEHICLE_REC_ID_ACK                  , 0x0000 },
            { Opcodes.CMSG_MOVE_SPLINE_DONE                             , 0x790E },
            { Opcodes.CMSG_MOVE_TIME_SKIPPED                            , 0x7A0A },
            // { Opcodes.CMSG_MOVE_TOGGLE_COLLISION_ACK                    , 0x0000 },
            { Opcodes.CMSG_MOVE_WATER_WALK_ACK                          , 0x3B00 },
            { Opcodes.CMSG_QUERY_PLAYER_NAME                            , 0x2224 },
            // { Opcodes.CMSG_NEW_SPELL_SLOT                               , 0x0000 },
            { Opcodes.CMSG_NEXT_CINEMATIC_CAMERA                        , 0x2014 },
            { Opcodes.CMSG_QUERY_NPC_TEXT                               , 0x4E24 },
            { Opcodes.CMSG_OBJECT_UPDATE_FAILED                         , 0x3808 },
            { Opcodes.CMSG_OBJECT_UPDATE_RESCUED                        , 0x3906 },
            { Opcodes.CMSG_OFFER_PETITION                               , 0x4817 },
            { Opcodes.CMSG_OPENING_CINEMATIC                            , 0x0A16 },
            { Opcodes.CMSG_OPEN_ITEM                                    , 0x6A34 },
            { Opcodes.CMSG_OPT_OUT_OF_LOOT                              , 0x6B16 },
            { Opcodes.CMSG_QUERY_PAGE_TEXT                              , 0x6614 },
            { Opcodes.CMSG_SILENCE_PARTY_TALKER                         , 0x6B26 }, // CGChat::SilencePartyMember (Audio)
            { Opcodes.CMSG_UNSILENCE_PARTY_TALKER                       , 0x4D24 }, // CGChat::SilencePartyMember (Audio)
            { Opcodes.CMSG_PETITION_BUY                                 , 0x4E05 },
            { Opcodes.CMSG_QUERY_PETITION                               , 0x4424 },
            { Opcodes.CMSG_PETITION_SHOW_LIST                           , 0x4617 },
            { Opcodes.CMSG_PETITION_SHOW_SIGNATURES                     , 0x4F15 },
            { Opcodes.CMSG_SIGN_PETITION                                , 0x0E04 },
            { Opcodes.CMSG_PET_ABANDON                                  , 0x0C24 },
            { Opcodes.CMSG_PET_ACTION                                   , 0x0226 },
            { Opcodes.CMSG_PET_CANCEL_AURA                              , 0x4B25 },
            { Opcodes.CMSG_PET_CAST_SPELL                               , 0x6337 },
            { Opcodes.CMSG_LEARN_PET_TALENTS                            , 0x6725 },
            // { Opcodes.CMSG_PET_NAME_CACHE                               , 0x0000 },
            { Opcodes.CMSG_QUERY_PET_NAME                               , 0x6F24 },
            { Opcodes.CMSG_PET_RENAME                                   , 0x6406 },
            { Opcodes.CMSG_PET_SET_ACTION                               , 0x6904 },
            { Opcodes.CMSG_PET_SPELL_AUTOCAST                           , 0x2514 },
            { Opcodes.CMSG_PET_STOP_ATTACK                              , 0x6C14 },
            { Opcodes.CMSG_PING                                         , 0x444D },
            { Opcodes.CMSG_REQUEST_PLAYED_TIME                          , 0x0804 },
            // { Opcodes.CMSG_PLAYER_DIFFICULTY_CHANGE                     , 0x0000 },
            { Opcodes.CMSG_PLAYER_LOGIN                                 , 0x05B1 },
            // { Opcodes.CMSG_PLAYER_LOGOUT                                , 0x0000 },
            { Opcodes.CMSG_RIDE_VEHICLE_INTERACT                        , 0x2705 },
            { Opcodes.CMSG_REQUEST_DANCE                                , 0x6914 },
            { Opcodes.CMSG_PUSH_QUEST_TO_PARTY                          , 0x4B14 },
            { Opcodes.CMSG_PVP_LOG_DATA                                 , 0x7308 },
            { Opcodes.CMSG_REQUEST_BATTLEFIELD_STATUS                   , 0x7202 },
            { Opcodes.CMSG_GUILD_QUERY_MEMBERS_FOR_RECIPE               , 0x1036 },
            { Opcodes.SMSG_GUILD_MEMBER_RECIPES                         , 0x1037 },
            { Opcodes.CMSG_GUILD_QUERY_RECIPES                          , 0x3033 },
            { Opcodes.CMSG_REQUEST_GUILD_REWARDS_LIST                   , 0x3012 },
            /// { Opcodes.CMSG_QUERY_GUILD_XP                               , 0x1237 },
            { Opcodes.CMSG_QUERY_INSPECT_ACHIEVEMENTS                   , 0x4D27 },
            /// { Opcodes.CMSG_QUERY_QUESTS_COMPLETED                       , 0x2317 },
            { Opcodes.CMSG_QUERY_TIME                                   , 0x0A36 },
            { Opcodes.SMSG_QUEST_CONFIRM_ACCEPT                         , 0x6B37 },
            // { Opcodes.CMSG_QUESTGIVER_CANCEL                            , 0x0000 },
            { Opcodes.CMSG_QUEST_GIVER_CHOOSE_REWARD                    , 0x2125 },
            { Opcodes.CMSG_QUEST_GIVER_COMPLETE_QUEST                   , 0x0114 },
            { Opcodes.CMSG_QUEST_GIVER_HELLO                            , 0x0D17 },
            { Opcodes.CMSG_QUEST_GIVER_QUERY_QUEST                      , 0x2F14 },
            // { Opcodes.CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                  , 0x0000 },
            { Opcodes.CMSG_QUEST_GIVER_REQUEST_REWARD                   , 0x2534 },
            { Opcodes.CMSG_QUEST_GIVER_STATUS_MULTIPLE_QUERY            , 0x6305 },
            { Opcodes.CMSG_QUEST_GIVER_STATUS_QUERY                     , 0x4407 },
            { Opcodes.CMSG_QUEST_LOG_REMOVE_QUEST                       , 0x0D16 },
            // { Opcodes.CMSG_QUESTLOG_SWAP_QUEST                          , 0x0000 },
            { Opcodes.CMSG_QUEST_CONFIRM_ACCEPT                         , 0x0D15 },
            /// { Opcodes.CMSG_QUEST_NPC_QUERY                              , 0x7302 },
            { Opcodes.CMSG_QUEST_POI_QUERY                              , 0x4037 },
            { Opcodes.CMSG_QUERY_QUEST_INFO                             , 0x0D06 },
            /// { Opcodes.CMSG_RANDOMIZE_CHAR_NAME                          , 0x2413 },
            /// { Opcodes.CMSG_READY_FOR_ACCOUNT_DATA_TIMES                 , 0x2B16 },
            { Opcodes.CMSG_READ_ITEM                                    , 0x2F16 },
            /// { Opcodes.CMSG_REALM_SPLIT                                  , 0x2906 },
            { Opcodes.CMSG_RECLAIM_CORPSE                               , 0x4036 },
            { Opcodes.CMSG_AUTH_CONTINUED_SESSION                       , 0x044D },
            /// { Opcodes.CMSG_REFORGE_ITEM                                 , 0x331A },
            { Opcodes.CMSG_REORDER_CHARACTERS                           , 0x0593 },
            { Opcodes.CMSG_REPAIR_ITEM                                  , 0x2917 },
            // { Opcodes.CMSG_REPLACE_ACCOUNT_DATA                         , 0x0000 },
            { Opcodes.CMSG_REPOP_REQUEST                                , 0x6235 },
            { Opcodes.CMSG_REPORT_PVP_PLAYER_AFK                        , 0x6734 },
            { Opcodes.CMSG_REQUEST_ACCOUNT_DATA                         , 0x6505 },
            { Opcodes.CMSG_REQUEST_CATEGORY_COOLDOWNS                   , 0x7102 },
            { Opcodes.CMSG_REQUEST_CEMETERY_LIST                        , 0x720A },
            { Opcodes.CMSG_HOTFIX_REQUEST                               , 0x2401 },
            /// { Opcodes.CMSG_REQUEST_INSPECT_RATED_BG_STATS               , 0x3010 },
            { Opcodes.CMSG_REQUEST_PARTY_MEMBER_STATS                   , 0x0C04 },
            { Opcodes.CMSG_REQUEST_PET_INFO                             , 0x4924 },
            { Opcodes.CMSG_GET_PVP_OPTIONS_ENABLED                      , 0x24A1 },
            { Opcodes.CMSG_REQUEST_PVP_REWARDS                          , 0x780C },
            { Opcodes.CMSG_REQUEST_RAID_INFO                            , 0x2F26 },
            { Opcodes.CMSG_REQUEST_RATED_BATTLEFIELD_INFO               , 0x2423 },
            /// { Opcodes.CMSG_REQUEST_RATED_BG_STATS                       , 0x05B3 },
            { Opcodes.CMSG_REQUEST_RESEARCH_HISTORY                     , 0x3306 },
            { Opcodes.CMSG_REQUEST_VEHICLE_EXIT                         , 0x2B35 },
            { Opcodes.CMSG_REQUEST_VEHICLE_NEXT_SEAT                    , 0x4434 },
            { Opcodes.CMSG_REQUEST_VEHICLE_PREV_SEAT                    , 0x4C04 },
            { Opcodes.CMSG_REQUEST_VEHICLE_SWITCH_SEAT                  , 0x4C14 },
            /// { Opcodes.CMSG_RESET_FACTION_CHEAT                          , 0x4469 },
            { Opcodes.CMSG_RESET_INSTANCES                              , 0x6E14 },
            { Opcodes.CMSG_RESURRECT_RESPONSE                           , 0x6827 },
            { Opcodes.CMSG_CLIENT_PORT_GRAVEYARD                        , 0x301E },
            { Opcodes.CMSG_INITIATE_ROLE_POLL                           , 0x0430 },
            { Opcodes.CMSG_SAVE_CUF_PROFILES                            , 0x730E },
            // { Opcodes.CMSG_SAVE_PLAYER                                  , 0x0000 },
            // { Opcodes.CMSG_SEARCH_LFG_JOIN                              , 0x0000 },
            // { Opcodes.CMSG_SEARCH_LFG_LEAVE                             , 0x0000 },
            { Opcodes.CMSG_SELF_RES                                     , 0x6115 },
            { Opcodes.CMSG_SELL_ITEM                                    , 0x4E15 },
            { Opcodes.CMSG_SEND_MAIL                                    , 0x0523 },
            { Opcodes.CMSG_SEND_SOR_REQUEST_VIA_ADDRESS                 , 0x0420 },
            /// { Opcodes.CMSG_SEND_SOR_REQUEST_VIA_BNET_ACCOUNT_ID         , 0x0482 },
            // { Opcodes.CMSG_SERVERTIME                                   , 0x0000 },
            // { Opcodes.CMSG_SETDEATHBINDPOINT                            , 0x0000 },
            { Opcodes.CMSG_SET_SHEATHED                                 , 0x4326 },
            { Opcodes.CMSG_SET_ACTION_BAR_TOGGLES                       , 0x2506 },
            { Opcodes.CMSG_SET_ACTION_BUTTON                            , 0x6F06 },
            { Opcodes.CMSG_SET_ACTIVE_MOVER                             , 0x3314 },
            /// { Opcodes.CMSG_SET_ACTIVE_VOICE_CHANNEL                     , 0x4305 }, // SetCurrentVoiceSession smth
            { Opcodes.CMSG_LOW_LEVEL_RAID1                              , 0x4435 },
            { Opcodes.CMSG_LOW_LEVEL_RAID2                              , 0x0536 },
            /// { Opcodes.CMSG_SET_CHANNEL_WATCH                            , 0x4517 },
            { Opcodes.CMSG_SET_CONTACT_NOTES                            , 0x6135 },
            { Opcodes.CMSG_SET_CURRENCY_FLAGS                           , 0x7306 },
            { Opcodes.CMSG_SET_EVERYONE_IS_ASSISTANT                    , 0x2530 },
            { Opcodes.CMSG_SET_FACTION_AT_WAR                           , 0x0706 },
            // { Opcodes.CMSG_SET_FACTION_CHEAT                            , 0x0000 },
            { Opcodes.CMSG_SET_FACTION_INACTIVE                         , 0x0E37 },
            { Opcodes.CMSG_GUILD_BANK_SET_TAB_TEXT                      , 0x3023 },
            // { Opcodes.CMSG_SET_LFG_COMMENT                              , 0x0000 },
            { Opcodes.CMSG_SET_PET_SLOT                                 , 0x3A04 },
            { Opcodes.CMSG_SET_PLAYER_DECLINED_NAMES                    , 0x6316 },
            { Opcodes.CMSG_SET_PREFERRED_CEMETERY                       , 0x311E },
            /// { Opcodes.CMSG_SET_PRIMARY_TALENT_TREE                      , 0x4524 },
            /// { Opcodes.CMSG_SET_RELATIVE_POSITION                        , 0x311A }, // setrawpos command (world position, not game coords)
            { Opcodes.CMSG_SET_SAVED_INSTANCE_EXTEND                    , 0x6706 },
            { Opcodes.CMSG_SET_SELECTION                                , 0x0506 },
            // { Opcodes.CMSG_SET_SKILL_CHEAT                              , 0x0000 },
            { Opcodes.CMSG_SET_TAXI_BENCHMARK_MODE                      , 0x4314 },
            { Opcodes.CMSG_SET_TITLE                                    , 0x2117 },
            { Opcodes.CMSG_SET_TRADE_CURRENCY                           , 0x3312 },
            { Opcodes.CMSG_SET_TRADE_GOLD                               , 0x3008 },
            { Opcodes.CMSG_SET_TRADE_ITEM                               , 0x7B0C },
            /// { Opcodes.CMSG_SET_VEHICLE_REC_ID_ACK                       , 0x3108 },
            { Opcodes.CMSG_SET_WATCHED_FACTION                          , 0x2434 },
            /// { Opcodes.CMSG_SHOWING_CLOAK                                , 0x4135 },
            /// { Opcodes.CMSG_SHOWING_HELM                                 , 0x0735 },
            { Opcodes.CMSG_SOCKET_GEMS                                  , 0x2F04 },
            { Opcodes.CMSG_SPELL_CLICK                                  , 0x0805 },
            { Opcodes.CMSG_SPIRIT_HEALER_ACTIVATE                       , 0x2E26 },
            { Opcodes.CMSG_SPLIT_ITEM                                   , 0x0F17 },
            { Opcodes.CMSG_STAND_STATE_CHANGE                           , 0x0535 },
            // { Opcodes.CMSG_START_QUEST                                  , 0x0000 },
            /// { Opcodes.CMSG_STOP_DANCE                                   , 0x2907 },
            // { Opcodes.CMSG_STORE_LOOT_IN_SLOT                           , 0x0000 },
            { Opcodes.CMSG_SUPPORT_TICKET_SUBMIT_BUG                    , 0x2520 },
            { Opcodes.CMSG_SUPPORT_TICKET_SUBMIT_COMPLAINT              , 0x2501 },
            { Opcodes.CMSG_SUPPORT_TICKET_SUBMIT_SUGGESTION             , 0x2512 },
            { Opcodes.CMSG_SUMMON_RESPONSE                              , 0x6F27 },
            /// { Opcodes.CMSG_SUSPEND_TOKEN                                , 0x046D },
            { Opcodes.CMSG_SWAP_INV_ITEM                                , 0x2614 },
            { Opcodes.CMSG_SWAP_ITEM                                    , 0x6326 },
            /// { Opcodes.CMSG_SYNC_DANCE                                   , 0x0036 },
            // { Opcodes.CMSG_TAXICLEARALLNODES                            , 0x0000 },
            // { Opcodes.CMSG_TAXIENABLEALLNODES                           , 0x0000 },
            { Opcodes.CMSG_TAXI_NODE_STATUS_QUERY                       , 0x2F25 },
            { Opcodes.CMSG_TAXI_QUERY_AVAILABLE_NODES                   , 0x6C06 },
            // { Opcodes.CMSG_TAXISHOWNODES                                , 0x0000 },
            /// { Opcodes.CMSG_TELEPORT_TO_UNIT                             , 0x4206 }, // (charm)port command
            { Opcodes.CMSG_SEND_TEXT_EMOTE                              , 0x2E24 },
            { Opcodes.CMSG_TIME_ADJUSTMENT_RESPONSE                     , 0x3818 },
            { Opcodes.CMSG_TIME_SYNC_RESPONSE                           , 0x3B0C },
            { Opcodes.CMSG_TIME_SYNC_RESPONSE_FAILED                    , 0x710A },
            { Opcodes.CMSG_TOGGLE_PVP                                   , 0x6815 },
            { Opcodes.CMSG_TOTEM_DESTROYED                              , 0x4207 },
            { Opcodes.CMSG_TRAINER_BUY_SPELL                            , 0x4415 },
            { Opcodes.CMSG_TRAINER_LIST                                 , 0x2336 },
            { Opcodes.CMSG_TRANSMOGRIFY_ITEMS                           , 0x3B0E },
            // { Opcodes.CMSG_TRIGGER_CINEMATIC_CHEAT                      , 0x0000 },
            { Opcodes.CMSG_TURN_IN_PETITION                             , 0x0B27 },
            /// { Opcodes.CMSG_TUTORIAL_CLEAR                               , 0x6515 },
            /// { Opcodes.CMSG_TUTORIAL_FLAG                                , 0x6C26 },
            /// { Opcodes.CMSG_TUTORIAL_RESET                               , 0x2726 },
            /// { Opcodes.CMSG_UNACCEPT_TRADE                               , 0x391A },
            { Opcodes.CMSG_UNLEARN_SKILL                                , 0x6106 },
            { Opcodes.CMSG_UNLEARN_SPECIALIZATION                       , 0x3210 },
            /// { Opcodes.CMSG_UNREGISTER_ALL_ADDON_PREFIXES                , 0x3D54 },
            { Opcodes.CMSG_UPDATE_ACCOUNT_DATA                          , 0x4736 },
            { Opcodes.CMSG_UPDATE_MISSILE_TRAJECTORY                    , 0x781E },
            /// { Opcodes.CMSG_UPDATE_PROJECTILE_POSITION                   , 0x0E24 },
            { Opcodes.CMSG_USED_FOLLOW                                  , 0x7912 },
            { Opcodes.CMSG_USE_ITEM                                     , 0x2C06 },
            { Opcodes.CMSG_VIOLENCE_LEVEL                               , 0x7816 },
            // { Opcodes.CMSG_VOICE_SESSION_ENABLE                         , 0x2314 },
            { Opcodes.CMSG_QUERY_VOID_STORAGE                           , 0x790A },
            { Opcodes.CMSG_VOID_STORAGE_TRANSFER                        , 0x380E },
            { Opcodes.CMSG_UNLOCK_VOID_STORAGE                          , 0x7B14 },
            { Opcodes.CMSG_SWAP_VOID_ITEM                               , 0x3204 },
            { Opcodes.CMSG_WARDEN_DATA                                  , 0x25A2 },
            { Opcodes.CMSG_ACCEPT_WARGAME_INVITE                        , 0x2410 }, // Not sure on this name
            { Opcodes.CMSG_START_WAR_GAME                               , 0x05A0 }, // Not sure on this name
            { Opcodes.CMSG_WHO                                          , 0x6C15 },
            { Opcodes.CMSG_WHO_IS                                       , 0x6B05 },
            { Opcodes.CMSG_UI_TIME_REQUEST                              , 0x4605 },
            /// { Opcodes.CMSG_WORLD_TELEPORT                               , 0x24B2 },
            { Opcodes.CMSG_WRAP_ITEM                                    , 0x4F06 },
            /// { Opcodes.CMSG_ZONE_UPDATE                                  , 0x4F37 },
        };

        private static BiDictionary<Opcodes, uint> _bidirectionalOpcodes = new BiDictionary<Opcodes, uint>()
        {

        };

        public uint OpcodeToValue(Opcodes opcode, PacketDirection direction)
        {
            if (_serverOpcodes.TryGetByFirst(opcode, out var value))
                return value;

            if (_bidirectionalOpcodes.TryGetByFirst(opcode, out value))
                return value;

            throw new InvalidProgramException("Unable to find opcode value for selected build");
        }

        public Opcodes ValueToOpcode(uint value, PacketDirection direction)
        {
            if (_serverOpcodes.TryGetBySecond(value, out var opcode))
                return opcode;

            if (_bidirectionalOpcodes.TryGetBySecond(value, out opcode))
                return opcode;

            throw new InvalidProgramException("Unable to find opcode value for selected build");
        }
    }
}
